from __future__ import annotations

from enum import StrEnum


class FailureCode(StrEnum):
    VALIDATION_FAILED_UNSUPPORTED_CLAIM = "VALIDATION_FAILED_UNSUPPORTED_CLAIM"
    VALIDATION_FAILED_CONTRADICTION = "VALIDATION_FAILED_CONTRADICTION"
    VALIDATION_FAILED_CRITICAL_OMISSION = "VALIDATION_FAILED_CRITICAL_OMISSION"
    VALIDATION_FAILED_SCHEMA = "VALIDATION_FAILED_SCHEMA"
    PROVIDER_OUTPUT_INVALID = "PROVIDER_OUTPUT_INVALID"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    WORKFLOW_TIMEOUT = "WORKFLOW_TIMEOUT"
    EXPORT_BLOCKED_DUE_TO_REJECTION = "EXPORT_BLOCKED_DUE_TO_REJECTION"


class WorkflowStage(StrEnum):
    INGEST = "ingest"
    NORMALIZE = "normalize"
    BIOMARKER_GRAPH = "biomarker_graph"
    DRAFT = "draft"
    VALIDATE = "validate"
    EVALUATE = "evaluate"
    EXPORT = "export"
